{"CVE Code": "CVE-2019-19275", "Description": "typed_ast 1.3.0 and 1.3.1 has an ast_for_arguments out-of-bounds read. An attacker with the ability to cause a Python interpreter to parse Python source (but not necessarily execute it) may be able to crash the interpreter process. This could be a concern, for example, in a web-based service that parses (but does not execute) Python code. (This issue also affected certain Python 3.8.0-alpha prereleases.)", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2019-19275", "Vulnerability Categories": "N/A", "Affected Products": "\nPython\u00bbTyped Ast\u00bbVersion:1.3.0cpe:2.3:a:python:typed_ast:1.3.0:*:*:*:*:*:*:*Matching versions\nPython\u00bbTyped Ast\u00bbVersion:1.3.1cpe:2.3:a:python:typed_ast:1.3.1:*:*:*:*:*:*:*Matching versions", "EPSS Score": "0.59% Probability of exploitation activity in the next 30 days\n~ 78 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n 1  2024-12-17  0.51%  0.59%  +0.08 \n 2  2024-11-19  0.32%  0.51%  +0.20 \n 3  2024-03-21  0.32%  0.32%  -0.01 \n 4  2023-10-17  0.24%  0.32%  +0.09 \n 5  2023-10-01  0.24%  0.24%  -0.01 \n 6  2023-09-15  0.20%  0.24%  +0.04 \n 7  2023-03-07  1.11%  0.20%  -0.91 ", "CVSS Scores": "5.0", "CWE": [{"CWE_ID": "CWE-125 Out-of-bounds Read", "CWE_link": "/cwe-details/125/Out-of-bounds-Read.html"}], "Reference": [{"ref_link": "https://bugs.python.org/issue36495", "ref_desc": "Issue 36495: Out-of-bounds array reads in Python/ast.c - Python trackerPatch;Vendor AdvisoryCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/3bJXwB8gl-AAOZGHopuCcIiKlWE.html"}, {"ref_link": "https://github.com/python/typed_ast/commit/dc317ac9cff859aa84eeabe03fb5004982545b3b", "ref_desc": "Fix two out-of-bounds array reads (#99) \u00b7 python/typed_ast@dc317ac \u00b7 GitHubPatch;Third Party AdvisoryCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/3vYdrSGVPrUThiDa6itOIN1R3bs.html"}, {"ref_link": "https://github.com/python/cpython/commit/dcfcd146f8e6fc5c2fc16a4c192a0c5f5ca8c53c", "ref_desc": "bpo-35766: Merge typed_ast back into CPython (GH-11645) \u00b7 python/cpython@dcfcd14 \u00b7 GitHubPatch;Third Party AdvisoryCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/KVvyck-Fi3fY6BeTrlfZjDTsQ_Y.html"}, {"ref_link": "https://github.com/python/cpython/commit/a4d78362397fc3bced6ea80fbc7b5f4827aec55e", "ref_desc": "bpo-36495: Fix two out-of-bounds array reads (GH-12641) \u00b7 python/cpython@a4d7836 \u00b7 GitHubPatch;Third Party AdvisoryCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/QrzuDtotNfkw0FkC1-OXzwwTHPg.html"}, {"ref_link": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LG5H4Q6LFVRX7SFXLBEJMNQFI4T5SCEA/", "ref_desc": "[SECURITY] Fedora 30 Update: python3-typed_ast-1.4.0-2.fc30 - package-announce - Fedora Mailing-ListsCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/SDS9nZqFhwBevlHViVpxCvfF65A.html"}, {"ref_link": "https://github.com/python/typed_ast/commit/156afcb26c198e162504a57caddfe0acd9ed7dce", "ref_desc": "Fully incorporate the code from Python 3.7.2 (#78) \u00b7 python/typed_ast@156afcb \u00b7 GitHubPatch;Third Party AdvisoryCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/ubjqVoI1PpZTXd8RQji0Cfprjv4.html"}]}