{"CVE Code": "CVE-2023-28858", "Description": "redis-py before 4.5.3 leaves a connection open after canceling an async Redis command at an inopportune time, and can send response data to the client of an unrelated request in an off-by-one manner. NOTE: this CVE Record was initially created in response to reports about ChatGPT, and 4.3.6, 4.4.3, and 4.5.3 were released (changing the behavior for pipeline operations); however, please see CVE-2023-28859 about addressing data leakage across AsyncIO connections in general.", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2023-28858", "Vulnerability Categories": "N/A", "Affected Products": "\nRedis\u00bbRedis-pyVersions  from including (>=) 4.2.0andbefore (<) 4.3.6cpe:2.3:a:redis:redis-py:*:*:*:*:*:*:*:*Matching versions\nRedis\u00bbRedis-pyVersions  from including (>=) 4.5.0andbefore (<) 4.5.3cpe:2.3:a:redis:redis-py:*:*:*:*:*:*:*:*Matching versions\nRedis\u00bbRedis-pyVersions  from including (>=) 4.4.0andbefore (<) 4.4.3cpe:2.3:a:redis:redis-py:*:*:*:*:*:*:*:*Matching versions", "EPSS Score": "0.14% Probability of exploitation activity in the next 30 days\n~ 50 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n 1  2024-10-16  0.14%  0.14%  0.00 \n 2  2024-09-05  0.12%  0.14%  +0.02 \n 3  2024-06-30  0.10%  0.12%  +0.01 \n 4  2024-04-27  0.10%  0.10%  +0.01 \n 5  2024-04-01  0.06%  0.10%  +0.03 \n 6  2024-02-24  0.06%  0.06%  +0.00 \n 7  2023-07-08  0.07%  0.06%  -0.01 \n 8  2023-07-03  0.06%  0.07%  +0.01 \n 9  2023-04-07  0.05%  0.06%  +0.01 \n 10  2023-04-06  0.04%  0.05%  +0.01 ", "CVSS Scores": "3.7", "CWE": [{"CWE_ID": "CWE-193 Off-by-one Error", "CWE_link": "/cwe-details/193/Off-by-one-Error.html"}], "Reference": [{"ref_link": "https://github.com/redis/redis-py/compare/v4.4.2...v4.4.3", "ref_desc": "Comparing v4.4.2...v4.4.3 \u00b7 redis/redis-py \u00b7 GitHubPatch", "ref_cve_link": "N/A"}, {"ref_link": "https://openai.com/blog/march-20-chatgpt-outage", "ref_desc": "March 20 ChatGPT outage: Here\u2019s what happenedThird Party Advisory", "ref_cve_link": "N/A"}, {"ref_link": "https://github.com/redis/redis-py/compare/v4.3.5...v4.3.6", "ref_desc": "Comparing v4.3.5...v4.3.6 \u00b7 redis/redis-py \u00b7 GitHubPatch", "ref_cve_link": "N/A"}, {"ref_link": "https://github.com/redis/redis-py/compare/v4.5.2...v4.5.3", "ref_desc": "Comparing v4.5.2...v4.5.3 \u00b7 redis/redis-py \u00b7 GitHubPatch", "ref_cve_link": "N/A"}, {"ref_link": "https://github.com/redis/redis-py/issues/2624", "ref_desc": "Off by 1 - Canceling async Redis command leaves connection open, in unsafe state for future commands \u00b7 Issue #2624 \u00b7 redis/redis-py \u00b7 GitHubIssue Tracking", "ref_cve_link": "N/A"}, {"ref_link": "https://github.com/redis/redis-py/pull/2641", "ref_desc": "AsyncIO Race Condition Fix by chayim \u00b7 Pull Request #2641 \u00b7 redis/redis-py \u00b7 GitHubIssue Tracking;PatchCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/UDnbtxWpp4z55PCHkti5vppZF7Q.html"}]}