{"CVE Code": "CVE-2017-5992", "Description": "Openpyxl 2.4.1 resolves external entities by default, which allows remote attackers to conduct XXE attacks via a crafted .xlsx document.", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2017-5992", "Vulnerability Categories": "XML external entity (XXE) injection", "Affected Products": "\nPython\u00bbOpenpyxl\u00bbVersion:2.4.1cpe:2.3:a:python:openpyxl:2.4.1:*:*:*:*:*:*:*Matching versions", "EPSS Score": "0.66% Probability of exploitation activity in the next 30 days\n~ 79 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n 1  2024-12-17  0.48%  0.66%  +0.18 \n 2  2023-07-03  0.48%  0.48%  +0.00 \n 3  2023-03-07  1.21%  0.48%  -0.73 ", "CVSS Scores": "5.8", "CWE": [{"CWE_ID": "CWE-611 Improper Restriction of XML External Entity Reference", "CWE_link": "/cwe-details/611/Improper-Restriction-of-XML-External-Entity-Reference.html"}], "Reference": [{"ref_link": "https://bitbucket.org/openpyxl/openpyxl/commits/3b4905f428e1", "ref_desc": "openpyxl / openpyxl / commit / 3b4905f428e1 \u2014 BitbucketIssue Tracking;Third Party Advisory", "ref_cve_link": "N/A"}, {"ref_link": "https://bitbucket.org/openpyxl/openpyxl/issues/749", "ref_desc": "openpyxl / openpyxl / issues / #749 - XXE vulnerability when loading workbook \u2014 BitbucketIssue Tracking;Third Party Advisory", "ref_cve_link": "N/A"}, {"ref_link": "http://www.openwall.com/lists/oss-security/2017/02/07/5", "ref_desc": "oss-security - CVE request: XXE in OpenpyxlMailing List;Third Party Advisory", "ref_cve_link": "N/A"}, {"ref_link": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854442", "ref_desc": "#854442 - XXE vulnerability in python-openpyxl - Debian Bug report logsIssue Tracking;Third Party Advisory", "ref_cve_link": "N/A"}]}