{"CVE Code": "CVE-2019-16226", "Description": "An issue was discovered in py-lmdb 0.97. mdb_node_del does not validate a memmove in the case of an unexpected node->mn_hi, leading to an invalid write operation. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker.", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2019-16226", "Vulnerability Categories": "Memory Corruption", "Affected Products": "\nPy-lmdb Project\u00bbPy-lmdbVersions  up to, including, (<=) 0.97cpe:2.3:a:py-lmdb_project:py-lmdb:*:*:*:*:*:*:*:*Matching versions", "EPSS Score": "0.17% Probability of exploitation activity in the next 30 days\n~ 54 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n 1  2024-12-17  0.16%  0.17%  +0.01 \n 2  2023-03-07  0.89%  0.16%  -0.73 ", "CVSS Scores": "5.0", "CWE": [{"CWE_ID": "CWE-787 Out-of-bounds Write", "CWE_link": "/cwe-details/787/Out-of-bounds-Write.html"}], "Reference": [{"ref_link": "https://github.com/TeamSeri0us/pocs/tree/master/lmdb/lmdb%20memory%20corruption%20vuln", "ref_desc": "pocs/lmdb/lmdb memory corruption vuln at master \u00b7 TeamSeri0us/pocs \u00b7 GitHubExploit;Third Party Advisory", "ref_cve_link": "N/A"}]}