{"CVE Code": "CVE-2021-28667", "Description": "StackStorm before 3.4.1, in some situations, has an infinite loop that consumes all available memory and disk space. This can occur if Python 3.x is used, the locale is not utf-8, and there is an attempt to log Unicode data (from an action or rule name).", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2021-28667", "Vulnerability Categories": "N/A", "Affected Products": "\nStackstorm\u00bbStackstormVersions  before (<) 3.4.1cpe:2.3:a:stackstorm:stackstorm:*:*:*:*:*:*:*:*Matching versionsWhen used together with:Python\u00bbPython", "EPSS Score": "0.10% Probability of exploitation activity in the next 30 days\n~ 42 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n 1  2023-12-01  0.09%  0.10%  +0.01 \n 2  2023-10-22  0.09%  0.09%  +0.00 \n 3  2023-03-07  0.89%  0.09%  -0.80 ", "CVSS Scores": "7.1", "CWE": [{"CWE_ID": "CWE-835 Loop with Unreachable Exit Condition ('Infinite Loop')", "CWE_link": "/cwe-details/835/Loop-with-Unreachable-Exit-Condition-Infinite-Loop-.html"}], "Reference": [{"ref_link": "https://stackstorm.com/2021/03/10/stackstorm-v3-4-1-security-fix/", "ref_desc": "StackStorm v3.4.1 - Security fix - StackStormPatch;Vendor Advisory", "ref_cve_link": "N/A"}]}