{"CVE Code": "CVE-2016-10149", "Description": "XML External Entity (XXE) vulnerability in PySAML2 4.4.0 and earlier allows remote attackers to read arbitrary files via a crafted SAML XML request or response.", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2016-10149", "Vulnerability Categories": "XML external entity (XXE) injection", "Affected Products": "\nDebian\u00bbDebian Linux\u00bbVersion:8.0cpe:2.3:o:debian:debian_linux:8.0:*:*:*:*:*:*:*Matching versions\nPysaml2 Project\u00bbPysaml2Versions  up to, including, (<=) 4.4.0cpe:2.3:a:pysaml2_project:pysaml2:*:*:*:*:*:*:*:*Matching versions", "EPSS Score": "0.21% Probability of exploitation activity in the next 30 days\n~ 58 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n 1  2024-12-17  0.32%  0.21%  -0.11 \n 2  2023-03-07  2.17%  0.32%  -1.86 ", "CVSS Scores": "5.0", "CWE": [{"CWE_ID": "CWE-611 Improper Restriction of XML External Entity Reference", "CWE_link": "/cwe-details/611/Improper-Restriction-of-XML-External-Entity-Reference.html"}], "Reference": [{"ref_link": "http://www.openwall.com/lists/oss-security/2017/01/19/5", "ref_desc": "oss-security - Re: CVE request: python-pysaml2 XML external entity attackMailing List;Patch;Third Party AdvisoryCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/9-dY0FygKKejnpNIWBkFrbGZe8s.html"}, {"ref_link": "https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b", "ref_desc": "Fix XXE in XML parsing (related to #366) \u00b7 IdentityPython/pysaml2@6e09a25 \u00b7 GitHubIssue Tracking;Patch;Third Party AdvisoryCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/EqxdJ1k2fqRelNtJj8eNwxzh0rk.html"}, {"ref_link": "https://github.com/rohe/pysaml2/pull/379", "ref_desc": "Fix XXE in XML parsing (related to #366) by fruechel \u00b7 Pull Request #379 \u00b7 IdentityPython/pysaml2 \u00b7 GitHubIssue Tracking;Patch;Third Party AdvisoryCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/G0JNXIZU62vZRbv6uhlIzT5oaLY.html"}, {"ref_link": "https://access.redhat.com/errata/RHSA-2017:0936", "ref_desc": "RHSA-2017:0936 - Security Advisory - Red Hat Customer Portal", "ref_cve_link": "N/A"}, {"ref_link": "https://github.com/rohe/pysaml2/issues/366", "ref_desc": "PySAML vulnerable to XXE \u00b7 Issue #366 \u00b7 IdentityPython/pysaml2 \u00b7 GitHubIssue Tracking;Patch;Third Party AdvisoryCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/nl3TljuSxdZcIhI72rdnuo5VZ-g.html"}, {"ref_link": "http://www.debian.org/security/2017/dsa-3759", "ref_desc": "Debian -- Security Information -- DSA-3759-1 python-pysaml2Third Party Advisory", "ref_cve_link": "N/A"}, {"ref_link": "http://www.securityfocus.com/bid/97692", "ref_desc": "python-pysaml2 CVE-2016-10149 XML Entity Expansion Denial of Service Vulnerability", "ref_cve_link": "N/A"}, {"ref_link": "https://access.redhat.com/errata/RHSA-2017:0937", "ref_desc": "RHSA-2017:0937 - Security Advisory - Red Hat Customer Portal", "ref_cve_link": "N/A"}, {"ref_link": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850716", "ref_desc": "#850716 - python-pysaml2: CVE-2016-10149 - Debian Bug report logsIssue Tracking;Patch;Third Party AdvisoryCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/YJed5m5MTOF1Jw5yXKp3G2U0pmk.html"}, {"ref_link": "https://access.redhat.com/errata/RHSA-2017:0938", "ref_desc": "RHSA-2017:0938 - Security Advisory - Red Hat Customer Portal", "ref_cve_link": "N/A"}]}