{"CVE Code": "CVE-2023-38898", "Description": "An issue in Python cpython v.3.7 allows an attacker to obtain sensitive information via the _asyncio._swap_current_task component. NOTE: this is disputed by the vendor because (1) neither 3.7 nor any other release is affected (it is a bug in some 3.12 pre-releases); (2) there are no common scenarios in which an adversary can call _asyncio._swap_current_task but does not already have the ability to call arbitrary functions; and (3) there are no common scenarios in which sensitive information, which is not already accessible to an adversary, becomes accessible through this bug.", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2023-38898", "Vulnerability Categories": "N/A", "Affected Products": "\nPython\u00bbPython\u00bbVersion:3.13.0UpdateAlpha0cpe:2.3:a:python:python:3.13.0:alpha0:*:*:*:*:*:*Matching versions", "EPSS Score": "0.08% Probability of exploitation activity in the next 30 days\n~ 36 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n 1  2024-09-16  0.07%  0.08%  +0.02 \n 2  2024-08-21  0.05%  0.07%  +0.01 \n 3  2024-07-15  0.05%  0.05%  +0.01 \n 4  2023-08-23  0.04%  0.05%  +0.00 ", "CVSS Scores": "5.3", "CWE": [], "Reference": [{"ref_link": "http://python.com", "ref_desc": "Not Applicable", "ref_cve_link": "N/A"}, {"ref_link": "https://github.com/python/cpython/issues/105987", "ref_desc": "Crash in `_asyncio._swap_current_task` due to improper reference counting \u00b7 Issue #105987 \u00b7 python/cpython \u00b7 GitHubExploit;Issue Tracking;Patch", "ref_cve_link": "N/A"}]}