{"CVE Code": "CVE-2024-35328", "Description": "libyaml v0.2.5 is vulnerable to a denial of service. Affected by this issue is the function yaml_parser_parse of the file /src/libyaml/src/parser.c. NOTE: this is disputed by the supplier because the discoverer's sample C code is incorrect: it does not call required _initialize functions that are described in the LibYAML documentation.", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2024-35328", "Vulnerability Categories": "Denial of service", "Affected Products": "\nPyyaml\u00bbLibyaml\u00bbVersion:0.2.5cpe:2.3:a:pyyaml:libyaml:0.2.5:*:*:*:*:*:*:*Matching versions\nPyyaml\u00bbLibyaml\u00bbVersion:0.2.5cpe:2.3:a:pyyaml:libyaml:0.2.5:*:*:*:*:*:*:*Matching versions", "EPSS Score": "0.04% Probability of exploitation activity in the next 30 days\n~ 10 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n 1  2024-08-29  0.05%  0.04%  0.00 \n 2  2024-07-20  0.04%  0.05%  +0.00 ", "CVSS Scores": "7.5", "CWE": [{"CWE_ID": "CWE-835 Loop with Unreachable Exit Condition ('Infinite Loop')", "CWE_link": "/cwe-details/835/Loop-with-Unreachable-Exit-Condition-Infinite-Loop-.html"}], "Reference": [{"ref_link": "https://github.com/idhyt/pocs/blob/main/libyaml/CVE-2024-35328.c", "ref_desc": "pocs/libyaml/CVE-2024-35328.c at main \u00b7 idhyt/pocs \u00b7 GitHubExploit", "ref_cve_link": "N/A"}, {"ref_link": "https://github.com/idhyt/pocs/tree/main/libyaml", "ref_desc": "pocs/libyaml at main \u00b7 idhyt/pocs \u00b7 GitHubCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/ZF0UDec0YL-9R-Fdc0M63XoA1Mw.html"}]}