{"CVE Code": "CVE-2024-53432", "Description": "While parsing certain malformed PLY files, PCL version 1.14.1 crashes due to an uncaught std::out_of_range exception in PCLPointCloud2::at. This issue could potentially be exploited to cause a denial-of-service (DoS) attack when processing untrusted PLY files.", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2024-53432", "Vulnerability Categories": "Denial of service", "Affected Products": "N/A", "EPSS Score": "0.04% Probability of exploitation activity in the next 30 days\n~ 10 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n Could not find any EPSS score change records for this CVE ", "CVSS Scores": "7.5", "CWE": [{"CWE_ID": "CWE-754 Improper Check for Unusual or Exceptional Conditions", "CWE_link": "/cwe-details/754/Improper-Check-for-Unusual-or-Exceptional-Conditions.html"}], "Reference": [{"ref_link": "https://github.com/PointCloudLibrary/pcl/issues/6162", "ref_desc": "Uncaught Exception in PCLPointCloud2::at When Parsing Malformed PLY Files (Potential DoS Vulnerability) \u00b7 Issue #6162 \u00b7 PointCloudLibrary/pcl \u00b7 GitHub", "ref_cve_link": "N/A"}]}